### ISSUE TITLE
Change GRPCInferenceService predict methods to use slash instead of colon

### ISSUE THREAD

**Issue by nosyliam** [metaprov/modelaapi#27]
https://github.com/metaprov/modelaapi/blob/0b8681b83921d358285ebce34c03cec4d5550ace/services/grpcinferenceservice/v1/grpcinferenceservice.proto#L101

These methods must use /predict. Kubernetes Ingress requires that prefixes be separated from their paths with a slash.

**Comment by tmeshorer** [comment]
But this is not a prefix, it is a suffix. ? 

Look at this:

https://github.com/googleforgames/open-match/blob/main/api/query.proto

**Comment by nosyliam** [comment]
This is an example Ingress rule which Modela creates to serve the Predictor over REST:
```yaml
    - host: predictors.serving.vcap.me
      http:
        paths:
          - backend:
              service:
                name: benchmark-car
                port:
                  number: 3001
            path: /v1/predictors/benchmark-car
            pathType: Prefix
```

If you attempt to send a request to `predictors.serving.vcap.me/v1/predictors/benchmark-car:predict` it does not work because the prefix must be separated by a slash. It recognizes the colon as part of the prefix and returns 404 not found. Kubernetes docs:
```Prefix: Matches based on a URL path prefix split by /. Matching is case sensitive and done on a path element by element basis. A path element refers to the list of labels in the path split by the / separator. A request is a match for path p if every p is an element-wise prefix of p of the request path.```
